transform_tolerance: 5.0  # 0.2

always_send_full_costmap: false

footprint: [[0.8,0.5],[0.8,-0.5],[-0.6,-0.5],[-0.6,0.5]]
# max_obstacle_height: 2.5

# map_type: voxel

obstacle_layer:
  unknown_threshold:    15
  mark_threshold:       0
  combination_method:   1
  track_unknown_space:  true    #true needed for disabling global path planning through unknown space
  obstacle_range: 5.5
  raytrace_range: 6.0
  # origin_z: 0.8
  # z_resolution: 0.4
  # z_voxels: 1
  # publish_voxel_map: false
  observation_sources: lidar
  lidar:
   data_type: PointCloud2
   topic: /velodyne_points
   marking: true
   clearing: true
   observation_persistence: 0.5
   min_obstacle_height: -0.5
   max_obstacle_height: 2.2

static_layer:
  unknown_cost_value: -1
  lethal_cost_threshold: 254
  first_map_only: false
  subscribe_to_updates: true
  track_unknown_space: true
  use_maximum: true
  trinary_costmap: true


inflation_layer:
  inflation_radius: 0.5  # the bigger the better, defines where the gradient is
  cost_scaling_factor: 1.0  # 0.5 the bigger the steeper the gradient is



# observation_sources: velodyne_points  #point_cloud_sensor #laser_scan_sensor

# # laser_scan_sensor: {sensor_frame: velodyne_1, data_type: LaserScan, topic: /scan, marking: true, clearing: true}

# velodyne_points: {sensor_frame: velodyne_1, data_type: PointCloud, topic: /velodyne_points, marking: true, clearing: true, min_obstacle_height: -5.25, max_obstacle_height: 5.5}
# # point_cloud_sensor: {sensor_frame: velodyne_1, data_type: PointCloud, topic: /velodyne_points, marking: true, clearing: true, min_obstacle_height: -5.25, max_obstacle_height: 5.5}

