global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 1.0
  publish_frequency: 1.0
  static_map: false
  rolling_window: true
  transform_tolerance: 5.1
  width: 50
  height: 50
  resolution: 0.1
  
