base_global_planner: "global_planner/GlobalPlanner"
# base_local_planner: "dwa_local_planner/DWAPlannerROS"
base_local_planner: "teb_local_planner/TebLocalPlannerROS"
recovery_behaviors: #[]
  - name: conservative_reset
    type: clear_costmap_recovery/ClearCostmapRecovery
  - name: agressive_reset
    type: clear_costmap_recovery/ClearCostmapRecovery
  
controller_frequency: 5.0
planner_frequency: 5.0  # 0. is only plan on a new goal or when local planner fails
planner_patience: 5.0
controller_patience: 5.0
recovery_behavior_enables: true
shutdown_costmaps: false
oscillation_timeout: 0.0  # 0. is infinite
oscillation_distance: 0.5
map_planning_retries: -1.  # -1 is infinite

# Planners
GlobalPlanner:
  allow_unknown: true
  default_tolerance: 0.0
  visualize_potential: true
  use_dijkstra: true  # although A* is faster, implementation pecularities here make it undesirable
  use_quadratic: true
  use_grid_path: false
  old_navfn_behavior: false
  lethal_cost: 253 #253 # how far from obstacle
  neutral_cost: 66 #40
  cost_factor:  0.55 #3
  publish_potential: True
  orientation_mode: 0
  orientation_window_size: 1

# Recovery behaviors
conservative_reset:
  reset_distance: 3.0

agressive_reset:
  reset_distance: 4.0
